version: '3.8'
services:
 mysql:
    image: mysql:8.0.23
    container_name: mysql
    restart: always
    env_file:
      - docker-secrets.env
    ports:
      - '3306:3306'
    expose:
      - '3306'      
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: