
########## APPLICATION NAME ###########
spring.application.name=chamados
server.port=8085
spring.jpa.database=MYSQL
spring.datasource.url=jdbc:mysql://localhost/db?useTimezone=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.show-sql=true
